jobs:
  include:

    - stage: "Install Dependencies"

      name: "Update apt packages"
      script: sudo apt-get update

      name: "Install the latest version of Go"
      script: sudo apt-get install golang-go
