jobs:
  include:

    - stage: "Install dependencies"

      script: sudo apt-get update
      name: "Update apt packages"

    - script: sudo apt-get install golang-go
      name: "Install the latest version of Go"

    - script: Installing apt dependencies
      name: "Installing apt dependencies"

    - script: yarn install --check-files --frozen-lockfile
      name: "Install node modules"
      language: node_js
      cache:
        directories:
          - node_modules
          - packages/gatsby-plugin-now/node_modules
          - packages/now-build-utils/node_modules
          - packages/now-cgi/node_modules
          - packages/now-cli/node_modules
          - packages/now-client/node_modules
          - packages/now-go/node_modules
          - packages/now-next/node_modules
          - packages/now-node/node_modules
          - packages/now-node-bridge/node_modules
          - packages/now-python/node_modules
          - packages/now-routing-utils/node_modules
          - packages/now-ruby/node_modules
          - packages/now-static-build/node_modules

    - stage: "Build"

      script: yarn bootstrap
      name: "Link dependencies"

      script: yarn build
      name: "Compile code"





