jobs:
  include:

    - stage: "Install dependencies"
      name: "Update apt packages"
      script: sudo apt-get update
      language: node_js

    - script: sudo apt-get install golang-go
      name: "Install the latest version of Go"

    - script: yarn install --check-files --frozen-lockfile
      name: "Install node modules"
