version: 2
jobs:

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - run: yarn run pack
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn test

  deploy-stable:
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "deploying stable"

  deploy-canary:
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "deploying canary now"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test
      - deploy-stable:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy-canary:
          requires:
            - build
            - test
          filters:
            branches:
              only: canary
