version: 2
jobs:

  install:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing Dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Compiling Binaries
          command: yarn run pack
      - persist_to_workspace:
          root: .
          paths:
            - packed

  test-lint:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Linting Code
          command: yarn test-lint

  test-unit:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running Unit Tests
          command: yarn test-unit

  deploy:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Installing Uploader
          command: go get github.com/tcnksm/ghr
      - run:
          name: Set GitHub Token
          command: git config --global github.token $GITHUB_TOKEN
      - run:
          name: Uploading Binaries
          command: ghr 11.0.0-canary.10 packed/*.gz
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  compile:
    jobs:
      - install
      - build:
          requires:
            - install
      - test-lint:
          requires:
            - build
      - test-unit:
          requires:
            - build
      - deploy:
          requires:
            - test-lint
            - test-unit
