version: 2
jobs:

  install:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Compiling binaries
          command: yarn run pack
      - persist_to_workspace:
          root: .
          paths:
            - packed

  test-lint:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Linting code
          command: yarn test-lint

  test-unit:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running unit tests
          command: yarn test-unit

  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Uploading binaries
          command: npx putasset --help

workflows:
  version: 2
  compile:
    jobs:
      - install
      - build:
          requires:
            - install
      - test-lint:
          requires:
            - build
      - test-unit:
          requires:
            - build
      - deploy:
          requires:
            - test-lint
            - test-unit
