name: Continuous Integration

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: node -v
      - name: Install
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: .

  test-unit:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
          name: build-output
      - name: Run Unit Tests
        run: yarn test-unit --clean false

  # test-lint:

  # test-now-cli:
  #   needs: build
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]
  #       node: [8, 10, 12]
  #   steps:
  #     - name: Now CLI

  # test-now-dev:
  #   needs: build

  # test-integration:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:

  # coverage:
  #   needs: [build, test-unit, test-now-cli, test-now-dev, test-integration]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Coverage
  #       run: yarn workspace now run coverage
