name: Inkeep Source Sync

on:
  push:
    branches:
      - main
    paths:
      - 'examples/docusaurus/**'
      
jobs:
  syncSourceJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            site:
              - 'examples/docusaurus/**'


      # Example for folder1 changes
      - name: Sync Site Source 
        if: steps.changes.outputs.site == 'true'
        uses: inkeep/source-sync-action@v3
        with:
          api-key: ${{ secrets.INKEEP_API_KEY }}
          source-id: 'clohl0lk20000s601g2siksub'

