name: Inkeep Source Sync

on:
  push:
    branches:
      - main
    paths:
      - 'examples/docusaurus/**'
      
jobs:
  syncSourceJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Example for folder1 changes
      - name: Sync Site Source 
        if: contains(github.event.head_commit.modified, 'examples/docusaurus/')
        uses: inkeep/source-sync-action@v1
        with:
          api-key: ${{ secrets.INKEEP_API_KEY }}
          source-id: 'clohl0lk20000s601g2siksub'

